-- 064: Booking links. The part a stranger touches.
-- Run in the Supabase SQL Editor. Idempotent.
--
-- 062 gave the calendar kinds of meeting. 063 gave the account a week it is
-- willing to be booked in. This is the door: a slug somebody who does not
-- have a login can open, see real free times on, and put a meeting in.
--
-- Three things make this different from everything before it.
--
--   1. The visitor is anonymous. Nothing here is readable by the anon role -
--      not one policy - because the public page is served by the API using
--      the service role and returns a hand-written list of fields. An RLS
--      policy that says "anyone may read booking_links" is one JOIN away
--      from leaking the rest of the account, and there is no version of
--      that trade worth making.
--
--   2. Two strangers can hit the same slot in the same second. The list of
--      times a booking page shows was computed when the page loaded, and
--      anything checked in the request handler is checked too late. The
--      real guard is book_slot() below: it takes a lock on the organiser,
--      re-checks the diary inside that lock, and inserts. Everything else
--      is advice.
--
--   3. A booking has to be undoable by someone with no account. That is
--      what manage_token is - an unguessable string, generated by the API,
--      that stands in for a login on exactly one meeting.

-- ---------------------------------------------------------------------------
-- 1. The links themselves
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS booking_links (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Globally unique, because it is the whole of the public URL. Lowercased
  -- on the way in so /Intro and /intro cannot be two different people.
  slug             text NOT NULL UNIQUE,
  -- Which kind of meeting this books. The kind carries the colour, the
  -- default length and where it happens, so a link is mostly a front door
  -- onto something the calendar already understands.
  event_type_id    uuid REFERENCES calendar_event_types(id) ON DELETE SET NULL,
  -- Overrides the kind's length when set. A link for a 15 minute version of
  -- a 30 minute meeting should not need a second kind.
  duration_minutes integer,
  headline         text NOT NULL,
  blurb            text,
  -- What the visitor is asked for beyond a name and an email.
  collect_phone    boolean NOT NULL DEFAULT false,
  collect_company  boolean NOT NULL DEFAULT false,
  -- One free-text question, asked of everybody. Null means do not ask.
  question         text,
  is_active        boolean NOT NULL DEFAULT true,
  -- Counters, so the list of links can say which one is actually working
  -- without a join onto every meeting ever booked.
  views            integer NOT NULL DEFAULT 0,
  bookings         integer NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  archived_at      timestamptz
);

DO $$
BEGIN
  -- A slug is the URL. Anything that needs escaping does not belong in one,
  -- and a single character is not a link, it is a collision waiting.
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'booking_links_slug_is_urlish') THEN
    ALTER TABLE booking_links ADD CONSTRAINT booking_links_slug_is_urlish
      CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'booking_links_headline_present') THEN
    ALTER TABLE booking_links ADD CONSTRAINT booking_links_headline_present
      CHECK (length(btrim(headline)) BETWEEN 1 AND 120);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'booking_links_duration_sane') THEN
    ALTER TABLE booking_links ADD CONSTRAINT booking_links_duration_sane
      CHECK (duration_minutes IS NULL OR duration_minutes BETWEEN 5 AND 1440);
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_booking_links_user ON booking_links (user_id, archived_at);

ALTER TABLE booking_links ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE tablename = 'booking_links'
       AND policyname = 'Users can manage their own booking links'
  ) THEN
    CREATE POLICY "Users can manage their own booking links"
      ON booking_links FOR ALL USING (auth.uid() = user_id);
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS trg_booking_links_updated_at ON booking_links;
CREATE TRIGGER trg_booking_links_updated_at
  BEFORE UPDATE ON booking_links
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 2. What a booked meeting remembers
--
-- A meeting booked by a stranger is still a crm_event - it draws on the same
-- grid, in the same colour, and counts against the same availability. These
-- columns are only the parts a meeting the account typed in itself does not
-- have.
-- ---------------------------------------------------------------------------

ALTER TABLE crm_events
  ADD COLUMN IF NOT EXISTS booking_link_id  uuid REFERENCES booking_links(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS booked_at        timestamptz,
  -- Stands in for a login on exactly one meeting, so the invitee can move or
  -- cancel it without an account. Generated by the API, never guessable.
  ADD COLUMN IF NOT EXISTS manage_token     text,
  -- What the invitee typed into the question, kept apart from the account's
  -- own notes so neither overwrites the other.
  ADD COLUMN IF NOT EXISTS invitee_message  text,
  -- The zone the invitee booked in. Without it, replying "does 3pm suit?" is
  -- a guess about whose 3pm.
  ADD COLUMN IF NOT EXISTS invitee_timezone text,
  ADD COLUMN IF NOT EXISTS cancelled_at     timestamptz,
  -- 'invitee' or 'organiser'. Who pulled out changes what you do next.
  ADD COLUMN IF NOT EXISTS cancelled_by     text,
  ADD COLUMN IF NOT EXISTS cancel_reason    text,
  -- Where it used to be, so a moved meeting still shows its own history.
  ADD COLUMN IF NOT EXISTS rescheduled_from timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'crm_events_cancelled_by_known') THEN
    ALTER TABLE crm_events ADD CONSTRAINT crm_events_cancelled_by_known
      CHECK (cancelled_by IS NULL OR cancelled_by IN ('invitee', 'organiser'));
  END IF;
END;
$$;

-- The manage link resolves by this and nothing else, so it has to be unique
-- and it has to be indexed. Partial, because every meeting typed in by hand
-- has no token and they must not all collide on null.
CREATE UNIQUE INDEX IF NOT EXISTS idx_crm_events_manage_token
  ON crm_events (manage_token) WHERE manage_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_crm_events_booking_link
  ON crm_events (booking_link_id, starts_at);

-- A view is worth counting but never worth failing a page load for, so it
-- goes through a function the API can call and ignore the result of.
CREATE OR REPLACE FUNCTION increment_link_views(p_link_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE booking_links SET views = views + 1 WHERE id = p_link_id;
$$;

DO $$
BEGIN
  EXECUTE 'REVOKE ALL ON FUNCTION increment_link_views(uuid) FROM PUBLIC';
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    EXECUTE 'REVOKE ALL ON FUNCTION increment_link_views(uuid) FROM anon';
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 3. The only thing standing between two strangers and the same slot
--
-- Everything about whether a time is offerable - working hours, notice,
-- the horizon, the daily cap - is decided in the API, because it is a policy
-- question and policy is easier to read in a language with words. This
-- function decides one thing only, and it is the thing that cannot be
-- decided anywhere else: is the diary still clear, right now, at the moment
-- of writing.
--
-- pg_advisory_xact_lock serialises bookings per organiser. It is keyed on
-- the user, not the slot, so two people booking different times on the same
-- calendar still queue behind each other - which is correct, because the
-- buffers mean a booking at 10:00 can invalidate one at 10:45. The lock
-- lifts when the transaction ends, either way.
--
-- Returns the new event id, or raises 'SLOT_TAKEN' which the API turns into
-- a 409 and a sentence about somebody having just taken it.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION book_slot(
  p_user_id          uuid,
  p_link_id          uuid,
  p_starts_at        timestamptz,
  p_ends_at          timestamptz,
  p_buffer_before    integer,
  p_buffer_after     integer,
  p_title            text,
  p_contact_id       uuid,
  p_contact_name     text,
  p_contact_email    text,
  p_invitee_message  text,
  p_invitee_timezone text,
  p_manage_token     text,
  p_event_type_id    uuid,
  p_location         text,
  p_exclude_event_id uuid DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_guard_start timestamptz;
  v_guard_end   timestamptz;
  v_clash       integer;
  v_id          uuid;
BEGIN
  -- Queue behind any other booking against this organiser.
  PERFORM pg_advisory_xact_lock(hashtext(p_user_id::text));

  v_guard_start := p_starts_at - make_interval(mins => COALESCE(p_buffer_before, 0));
  v_guard_end   := p_ends_at   + make_interval(mins => COALESCE(p_buffer_after, 0));

  /*
   * Anything in the diary that overlaps the guarded window.
   *
   * COALESCE on ends_at because a meeting may only imply its length; an
   * hour is the safer assumption than treating it as instantaneous, which
   * would let a booking land on top of it. An all-day event blocks its
   * whole day. p_exclude_event_id is the meeting being moved, which must
   * not be found clashing with itself.
   */
  SELECT count(*) INTO v_clash
    FROM crm_events e
   WHERE e.user_id = p_user_id
     AND e.status <> 'cancelled'
     AND (p_exclude_event_id IS NULL OR e.id <> p_exclude_event_id)
     AND (
       CASE WHEN e.all_day
            THEN tstzrange(date_trunc('day', e.starts_at),
                           date_trunc('day', e.starts_at) + interval '1 day', '[)')
            ELSE tstzrange(e.starts_at,
                           COALESCE(e.ends_at, e.starts_at + interval '1 hour'), '[)')
       END
     ) && tstzrange(v_guard_start, v_guard_end, '[)');

  IF v_clash > 0 THEN
    RAISE EXCEPTION 'SLOT_TAKEN' USING ERRCODE = 'unique_violation';
  END IF;

  IF p_exclude_event_id IS NULL THEN
    INSERT INTO crm_events (
      user_id, title, type, starts_at, ends_at,
      contact_id, contact_name, contact_email,
      booking_link_id, booked_at, manage_token,
      invitee_message, invitee_timezone,
      event_type_id, location, status
    ) VALUES (
      p_user_id, p_title, 'meeting', p_starts_at, p_ends_at,
      p_contact_id, p_contact_name, p_contact_email,
      p_link_id, now(), p_manage_token,
      p_invitee_message, p_invitee_timezone,
      p_event_type_id, p_location, 'confirmed'
    ) RETURNING id INTO v_id;

    UPDATE booking_links SET bookings = bookings + 1 WHERE id = p_link_id;
  ELSE
    -- Moving one that already exists. Its history moves with it.
    UPDATE crm_events
       SET rescheduled_from = starts_at,
           starts_at        = p_starts_at,
           ends_at          = p_ends_at,
           status           = 'confirmed',
           cancelled_at     = NULL,
           cancelled_by     = NULL,
           cancel_reason    = NULL
     WHERE id = p_exclude_event_id
       AND user_id = p_user_id
    RETURNING id INTO v_id;

    IF v_id IS NULL THEN
      RAISE EXCEPTION 'NO_SUCH_BOOKING' USING ERRCODE = 'no_data_found';
    END IF;
  END IF;

  RETURN v_id;
END;
$$;

-- The API calls this as the service role. Nobody else needs it, and the anon
-- role must never reach it - a SECURITY DEFINER function callable by the
-- public is a way to write to any account's calendar.
--
-- The anon and authenticated roles are revoked by name rather than relying on
-- PUBLIC, because a later GRANT to either would otherwise go unnoticed. Both
-- are wrapped in an existence check: this file has to apply cleanly on a
-- plain Postgres too, where neither role exists, and a bare REVOKE against a
-- missing role aborts the whole script.
DO $$
DECLARE
  v_sig text := 'book_slot(uuid, uuid, timestamptz, timestamptz, integer, integer,'
             || ' text, uuid, text, text, text, text, text, uuid, text, uuid)';
  v_role text;
BEGIN
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC', v_sig);
  FOREACH v_role IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = v_role) THEN
      EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %I', v_sig, v_role);
    END IF;
  END LOOP;
END;
$$;

-- ---------------------------------------------------------------------------
-- 4. A link to start from
--
-- Every account that already exists gets one, pointed at its default kind of
-- meeting, inactive until it is looked at. A scheduler whose first screen is
-- an empty list with a "create" button teaches nobody what it is for.
--
-- The slug is derived from the account id rather than the email: an email
-- local part can contain anything, collides across domains, and putting it
-- in a public URL tells a stranger the address before they have earned it.
-- ---------------------------------------------------------------------------

INSERT INTO booking_links (user_id, slug, event_type_id, headline, blurb, is_active)
SELECT u.id,
       'meet-' || substr(replace(u.id::text, '-', ''), 1, 10),
       (SELECT t.id FROM calendar_event_types t
         WHERE t.user_id = u.id AND t.is_default AND t.archived_at IS NULL
         LIMIT 1),
       'Book a time with me',
       'Pick whatever suits. You will get a confirmation straight away.',
       false
  FROM auth.users u
 WHERE NOT EXISTS (SELECT 1 FROM booking_links b WHERE b.user_id = u.id)
ON CONFLICT (slug) DO NOTHING;
